DROP TABLE IF EXISTS Retter;
DROP TABLE IF EXISTS Varer;
DROP TABLE IF EXISTS RetterVarer;
DROP TABLE IF EXISTS Kategorier;

CREATE TABLE Retter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  navn TEXT UNIQUE NOT NULL,
  sideret INTEGER NOT NULL
);

CREATE TABLE Varer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  navn TEXT UNIQUE NOT NULL,
  kategori_id INTEGER NOT NULL
);

CREATE TABLE RetterVarer (
  ret_id INTEGER NOT NULL,
  vare_id INTEGER NOT NULL,
  antal REAL NOT NULL,
  FOREIGN KEY (ret_id) REFERENCES Retter (id),
  FOREIGN KEY (vare_id) REFERENCES Varer (id),
  UNIQUE(ret_id, vare_id)
);

CREATE TABLE Kategorier (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  navn TEXT UNIQUE NOT NULL,
  sortering INTEGER NOT NULL
);