DROP TABLE IF EXISTS Retter;
DROP TABLE IF EXISTS Varer;
DROP TABLE IF EXISTS RetterVarer;

CREATE TABLE Retter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  navn TEXT UNIQUE NOT NULL
);

CREATE TABLE Varer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  navn TEXT UNIQUE NOT NULL,
  kategori TEXT UNIQUE NOT NULL
);

CREATE TABLE RetterVarer (
  ret_id INTEGER NOT NULL,
  vare_id INTEGER NOT NULL,
  antal INTEGER NOT NULL,
  FOREIGN KEY (ret_id) REFERENCES Retter (id)
  FOREIGN KEY (vare_id) REFERENCES Varer (id)
);
